add rpcInfo to context in serverStream
grpc/grpc-go pull request #3480
Opened 2020-03-27 12:15 UTC by eafzali

to use `PreparedMsg` in `ServerStream`.

2020-04-09 20:40 UTC, easwars commented
Could you please sign the CLA. Thanks.

2020-08-10 18:05 UTC, eafzali commented
Any update on this?

2020-08-10 22:37 UTC, dfawley commented
Sorry, I still need to do some digging into the initial PR/issue to find out whether this is something we didn't do on purpose or whether it was something we didn't think about / forgot about.

2020-08-10 22:37 UTC, dfawley commented
Also it seems travis didn't run.  I will close & reopen to see if that helps.

2020-09-17 10:15 UTC, eafzali commented
@dfawley could you find anything?

2021-05-04 23:29 UTC, dfawley requested changes
Sorry for the long delay.  I spent some time today digging into the old issue and the code, and it seems this was omitted because nobody asked for it / thought to implement it.  It "just works" like this as long as we add the codec info into the context because of the way it was implemented.  Very cool that it was so simple.

A few comments on the test are inline.

Please also rebase your branch to master@HEAD to pick up the new tests (mostly to get rid of the old ones) and some flaky test fixes.

Thanks for the PR!

2021-05-04 23:29 UTC, dfawley commented on test/end2end_test.go
> +	stream.SendMsg(preparedMsg)
Could you repeat this call a few times and verify it on the client?

2021-05-04 23:29 UTC, dfawley commented on test/end2end_test.go
> +	}
This isn't really the type of test we write anymore.  Please take a look at https://github.com/grpc/grpc-go/blob/4f3aa7cfa157c38bd5c2da7f4568614f815ab4ad/test/end2end_test.go#L5260 for an example.  This should hopefully make things a lot simpler (no need to make your own Server struct, e.g.)

2021-05-04 23:29 UTC, dfawley commented on test/end2end_test.go
> +			Body: []byte{'0'},
Please make this a bit more complex to improve confidence.

2021-05-19 18:19 UTC, dfawley commented
@eafzali I notice you did a force push, but I don't see any changes that address my comments.  Can you update us on the status of this PR?

2021-05-20 15:04 UTC, eafzali commented
yea sorry, I just rebased and forced push but didn't have time to address your comments. can you take a look again

2021-05-21 22:52 UTC, dfawley approved these changes

2021-05-21 22:54 UTC, dfawley commented
> yea sorry, I just rebased and forced push but didn't have time to address your comments. can you take a look again

No worries; thank you for the PR!

2021-05-21 22:54 UTC, merged