Standardized "experimental" warnings across all packages
grpc/grpc-go pull request #3917
Opened 2020-10-01 04:03 UTC by gauravgahlot

Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>

Fixes: #3605

2020-10-01 04:06 UTC, gauravgahlot commented
@easwars @dfawley
Could you please add the `no release notes` label? 
Please take a look at the changes.

2020-10-01 17:24 UTC, easwars requested changes

2020-10-01 17:24 UTC, easwars commented on attributes/attributes.go
> +// Notice: This package is experimental and may be changed or removed in a
Nit: In all places where we say "This package/type/API is experimental", could you please make the experimental all caps. Thank you. 

Example: https://github.com/grpc/grpc-go/blob/master/credentials/xds/xds.go#L24

2020-10-02 16:10 UTC, easwars approved these changes
Thanks for the PR!!

2020-10-02 16:11 UTC, merged