Remove experimental comment from client interceptors
grpc/grpc-go pull request #3948
Opened 2020-10-10 20:20 UTC by hypnoglow

As proposed per https://github.com/grpc/grpc-go/issues/3693, this change removes comments stating that client interceptors API are still experimental.

I added additional commentary on parameters and return values etc. as far as I understand them. Please let me know if we need to rephrase/add/remove those comments.

2020-10-10 20:20 UTC, hypnoglow commented
/assign @dfawley

2020-10-13 17:24 UTC, easwars requested changes
Thank you very much for the PR.

2020-10-13 17:24 UTC, easwars commented on interceptor.go
> +// UnaryClientInterceptor intercepts the execution of a unary RPC on the client. The interceptors can be set on the
Minor modifications:

```
// UnaryClientInterceptor intercepts the execution of a unary RPC on the client.
// Unary interceptors can be specified as a DialOption, using WithUnaryInterceptor() or 
// WithChainUnaryInterceptor(), when creating a ClientConn. When a unary interceptor(s)
// is set on a ClientConn, gRPC delegates all unary RPC invocations to the interceptor,
// and it is the responsibility of the interceptor to call invoker to complete the processing
// of the RPC.
//
// method is the RPC name. req and reply are the corresponding request and response messages.
// cc is the ClientConn on which the RPC was invoked. invoker is the handler to complete the RPC
// and it is the responsibility of the interceptor to call it. opts contain all applicable call options,
// including defaults from the ClientConn as well as per-call options.
//
// The returned error must be compatible with the status package.

```

2020-10-13 17:24 UTC, easwars commented on interceptor.go
> +// method is RPC name. req and reply are corresponding request and response RPC messages. cc is the client connection
Nit: Could you also please make sure the comment lines are wrapped at 80 cols. Thanks.

2020-10-13 17:24 UTC, easwars commented on interceptor.go
> +// StreamClientInterceptor intercepts the creation of ClientStream. The interceptors can be set on the client connection
Similar comments here:
```
// StreamClientInterceptor intercepts the creation of a ClientStream. Stream interceptors can be specified as a
// DialtOption, using WithStreamInterceptor() or WithChainStreamInterceptor(), when creating a ClientConn. When
// a stream interceptor(s) is set on the ClientConn, gRPC delegates all stream creations to the interceptor, and it 
// is the responsibility of the interceptor to call streamer.
//
// desc contains a description of the stream. cc is the ClientConn on which the RPC was invoked. 
// streamer is the handler to create a ClientStream and it is the responsibility of the interceptor to call it.
// opts contain all applicable call options, including defaults from the ClientConn as well as per-call options.
//
// StreamClientInterceptor may return a custom ClientStream to intercept all I/O operations.
// The returned error must be compatible with the status package
```

2020-10-24 19:56 UTC, hypnoglow commented
@easwars Thank you for the review. Updated the comments and wrapped at 80 cols.

2020-10-26 14:33 UTC, easwars approved these changes
Thank you very much for the PR.

2020-10-26 14:33 UTC, merged