Fixed: Avoid using context.Background in tests
grpc/grpc-go pull request #3949
Opened 2020-10-10 20:26 UTC by gauravgahlot

Fixes: #1878

2020-10-10 20:30 UTC, gauravgahlot commented
I have intentionally split the changes into commits based on the parent directory. This will make it easier for me to do any changes suggested during the review. 

@dfawley Could you please add `no release notes` label and also take a look at the changes?

2020-10-13 17:34 UTC, easwars requested changes
We don't want to change `context.Background()` with `context.TODO()`. What we want instead is what @dfawley mentioned in https://github.com/grpc/grpc-go/issues/1878#issuecomment-702970169.

Each test file (one per package) should define a `defaultTestTimeout`. And each test must create a local context with the appropriate timeout.

```
const defaultTestTimeout = 10 * time.Second

func TestXxx(t *testing.T) {
  ctx, cancel := context.WithTimeout(defaultTestTimeout)
  defer cancel()

  // Do stuff and pass `ctx` to functions which accept one.
}
```

And for places where we block on some event *not* happening, we should define a much shorter timeout (something of the order of 10ms), create a new context with that short deadline, and use that.

Hope this helps.

Thanks.

2020-10-15 05:15 UTC, gauravgahlot commented
Thanks for the explanation @easwars. I clearly misinterpreted @dfawley's comment. 

I have made changes to the last commit. Please take a look and let me know if I'm doing it right this time.
If so, I will update the rest of the commits.

Thanks again. :)

2020-10-15 16:49 UTC, easwars requested changes
I checked the last commit. The changes look mostly OK. I left some minor comments. Thank you so very much for doing this.

2020-10-15 16:49 UTC, easwars commented on benchmark/primitives/context_test.go
> +	pCtx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
Here, we are testing `context.WithValue()`, so it is totally OK to use the background context.

What you can fix here though are the `BenchmarkTimer*` functions. Those are using arbitrary large values, those should be changed use the `defaultTestTimeout`.

2020-10-15 16:49 UTC, easwars commented on metadata/metadata_test.go
> +		ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
This should probably be moved to be outside the `for` loop. Thanks.

2020-10-15 16:49 UTC, easwars commented on stats/stats_test.go
> +	ctx := metadata.NewOutgoingContext(tCtx, testMetadata)
This call to `metadata.NewOutgoingContext()` could be inlined within the `UnaryCall`, just like how it is done for the `FullDuplexCall`.

2020-10-30 16:52 UTC, easwars approved these changes
Thank you so very much.

2020-10-30 16:52 UTC, easwars commented on test/end2end_test.go
> +	ctx, cancel = context.WithTimeout(context.Background(), defaultTestTimeout)
Can't we use the `ctx` created in line 1272 here? And do a `defer cancel()`

2020-11-03 19:16 UTC, easwars commented
@gauravgahlot : Could you please take care of the test failure here: https://github.com/grpc/grpc-go/pull/3949/checks?check_run_id=1340435962. Thanks.

2020-11-05 04:26 UTC, gauravgahlot commented
@easwars I have fixed the issue and it should be good to go now. 🚀

2020-11-05 17:25 UTC, merged