xds: add support for HTTP filters (gRFC A39)
grpc/grpc-go pull request #4206
Opened 2021-02-16 23:20 UTC by dfawley

This is a fairly large PR, so apologies for that up-front.

I would recommend reviewing in this order:

1. `httpfilter.go` and `config_selector.go` - main interface definitions
2. `xds/internal/client` - parsing/validation of xds data
3. `xds/internal/resolver` - usage of the parsed HTTP filter config
4. leftovers: router plugin (a fancy nop), `stream.go`/`transport` code to signal interceptors when RPC is completed (done with connection; needed for fault injection functionality - coming soon)

2021-02-23 21:22 UTC, menghanl requested changes
> Reviewed 7 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4206)* status: 7 of 18 files reviewed, 10 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[stream.go, line 192 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFjZIgE-oSqZ6PCFu1:-MUFjZIgE-oSqZ6PCFu2:bugyjl7) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/stream.go#L192)):*
> ```Go
> 		if rpcConfig.Interceptor != nil {
> 			rpcInfo.Context = nil
> 			newCtx, cs, err := rpcConfig.Interceptor.NewStream(ctx, rpcInfo, iresolver.NOPClientStream{})
> ```

Why is this using a NOP stream?

I think we should try to use the real stream, even though it's not necessary now.
Otherwise, the API seems incomplete.

If time is the concern here, just pass `nil` then?
___
*[internal/resolver/config_selector.go, line 64 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFhk5D90FZgc5zVk-U:-MUFhk5D90FZgc5zVk-V:bkqkbm5) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/internal/resolver/config_selector.go#L64)):*
> ```Go
> 	// ClientStream after done is called, since the interceptor is invoked by
> 	// application-layer operations.
> 	Done()
> ```

`Done(DoneInfo)`?
___
*[internal/resolver/config_selector.go, line 76 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFk3aA7atqvt6A9MC7:-MUFk3aA7atqvt6A9MC8:budmuc9) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/internal/resolver/config_selector.go#L76)):*
> ```Go
> 
> // ClientInterceptor is an interceptor for gRPC client streams.
> type ClientInterceptor interface {
> ```

What's the reason to not just use the old interceptors?
Dependency problem?
Or because of the `Done` function?
___
*[internal/resolver/config_selector.go, line 80 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFiaNM6Uzk3eA_66ZZ:-MUFiaNM6Uzk3eA_66Z_:b7ct2yd) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/internal/resolver/config_selector.go#L80)):*
> ```Go
> 	// should not be used during NewStream.  RPCInfo.Context should not be used
> 	// (will be nil).
> 	NewStream(context.Context, RPCInfo, ClientStream) (context.Context, ClientStream, error)
> ```

If `ClientInterceptor` is picked from `ConfigSelector`, it should already have `RPCInfo`, right? So we don't need it again?
___
*[internal/resolver/config_selector.go, line 84 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFi1_F0yP8rKxlvi4I:-MUFi1_F0yP8rKxlvi4J:bhxpam7) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/internal/resolver/config_selector.go#L84)):*
> ```Go
> 
> // ServerInterceptor is unimplementable; do not use.
> type ServerInterceptor interface {
> ```

Are there plans to support this in the near future?
___
*[xds/internal/httpfilter/httpfilter.go, line 39 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFTKEKEq5W-kH04yC3:-MUFTKEKEq5W-kH04yC4:b-3kd2fl) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/xds/internal/httpfilter/httpfilter.go#L39)):*
> ```Go
> // client side or server side or both, respectively.
> type Filter interface {
> 	// TypeURLs are the registered proto message types supported by this filter.
> ```

Add something like `This filter will be registered for each of the returned URLs.`
___
*[xds/internal/httpfilter/httpfilter.go, line 42 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFTXnw0MMC8LmVtOM4:-MUFTXnw0MMC8LmVtOM5:b-c0oswc) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/xds/internal/httpfilter/httpfilter.go#L42)):*
> ```Go
> 	TypeURLs() []string
> 	// ParseFilterConfig parses the provided configuration proto.Message.  This
> 	// may be an anypb.Any or a udpa.type.v1.TypedStruct for filters that do
> ```

What type to accept should be a detail of the implementation, not the interface, right?
___
*[xds/internal/httpfilter/httpfilter.go, line 46 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFTlu62QKvVxIxmELV:-MUFTlu62QKvVxIxmELW:b9ahoos) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/xds/internal/httpfilter/httpfilter.go#L46)):*
> ```Go
> 	// passed to Build.
> 	ParseFilterConfig(proto.Message) (FilterConfig, error)
> 	// ParseFilterConfigOverrid parses the provided override configuration
> ```

Document how this is different from `ParseFilterConfig()`?
Is this basically the same method, but not as strict?
___
*[xds/internal/httpfilter/httpfilter.go, line 89 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFUX667gjdZFo74HQb:-MUFUX667gjdZFo74HQc:b-9f671k) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/xds/internal/httpfilter/httpfilter.go#L89)):*
> ```Go
> // an init() function), and is not thread-safe. If multiple filters are
> // registered with the same type URL, the one registered last will take effect.
> func Register(b Filter) {
> ```

What if the `Filter` doesn't implement `Client` or `Server`?
___
*[xds/internal/httpfilter/router/router.go, line 42 at r1](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUFVMGZ2dBXf1lW2V0q:-MUFVMGZ2dBXf1lW2V0r:b-gehs59) ([raw file](https://github.com/grpc/grpc-go/blob/0d388b6029cd3e1d67fb8fb6da63faa3acbc9c2b/xds/internal/httpfilter/router/router.go#L42)):*
> ```Go
> 
> // IsRouterFilter returns true iff a HTTP filter is a Router filter.
> func IsRouterFilter(b httpfilter.Filter) bool {
> ```

Is "router" a category of "filter"?
What if `b` embeds a `*builder`?

And will we still need this if `ParseFilterConfig` actually does parsing, and return error if config is invalid? Can we use that instead?


<!-- Sent from Reviewable.io -->

2021-02-23 21:50 UTC, dfawley commented
> Why is this using a NOP stream?
>
> I think we should try to use the real stream, even though it's not necessary now.
> Otherwise, the API seems incomplete.
>
> If time is the concern here, just pass nil then?

Yes, the API is incomplete. `nil` doesn't work, since we need an underlying `Done` defined, to be called by the interceptor's `Done` method.  We could do `nil` checks in all interceptors instead, but this way is nicer.

> Done(DoneInfo)?

This is an internal-only API, so we don't need to future-proof it.

> What's the reason to not just use the old interceptors?
> Dependency problem?
> Or because of the Done function?

Three reasons:

1. It's the wrong domain. These functions are not invoked by the API layer, so they don't want things like `CallOption`s.
2. Circular dependency problem.
3. `Done`.

> If ClientInterceptor is picked from ConfigSelector, it should already have RPCInfo, right? So we don't need it again?

Including it here makes interceptors reusable.  I.e. we can build/cache one interceptor for each route, and not need to reconstruct.  I'm not doing that in this PR, but that's why I passed it here.

>> ...`ServerInterceptor`...
> Are there plans to support this in the near future?

It's not too far off.  @easwars will need to implement these eventually before we release server-side support.

> Add something like This filter will be registered for each of the returned URLs.

Done

> What type to accept should be a detail of the implementation, not the interface, right?

You would think so.  But this is actually an important part of the API.  We never call `Parse` with anything besides a `*anypb.Any` or a `*udpa.type.v1.TypedStruct`.

> Document how this is different from ParseFilterConfig()?
> Is this basically the same method, but not as strict?

The only difference is the source of the configuration passed to it.  "Strictness" depends upon the implementation.  Updated.

> What if the Filter doesn't implement Client or Server?

Then Doom On You!  In reality, it means it won't be recognized by either side.  It can parse configs, but can't function.  So we will fail validation of this filter and NACK if it's in LDS (since we check client/server capability depending on the listener), but will pass validation in RDS (since we don't know whether it's intended for the client or server).

> Is "router" a category of "filter"?

`router` *is* a filter.

> What if b embeds a *builder?

Who would do that?  Remember, this is all internal.

The goal here is to recognize the router filter when we find it in the list of filters.  The router filter is special because it is (currently?) implemented by a ton of hard-coded logic in the xds resolver.  If it's absent, we will fail RPCs.  If it's present, we ignore any filters after it.

> And will we still need this if ParseFilterConfig actually does parsing, and return error if config is invalid? Can we use that instead?

`ParseFilterConfig` doesn't do parsing today because we don't support any of the configuration for the router filter.  When we need to support that configuration, there's a couple options:

1. Implement the router filter like any other filter (but maybe with some kind of special operations it can perform since it needs to actually do the routing step?).
2. Export the configuration type so the xds resolver can read that configuration and act upon it.

2021-02-23 23:34 UTC, menghanl requested changes
> Reviewed 6 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4206)* status: 13 of 18 files reviewed, 12 unresolved discussions (waiting on @dfawley and @menghanl)

___
*[xds/internal/client/lds_test.go, line 419 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUG6TgA5OHQR7M5GBxv:-MUG6TgB3MCm0iNJePXd:bpxjow8) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/client/lds_test.go#L419)):*
> ```Go
> 			if ((err != nil) != test.wantErr) ||
> 				!cmp.Equal(update, test.wantUpdate, cmpopts.EquateEmpty(),
> 					cmp.Transformer("any", func(a *anypb.Any) string {
> ```

This handles all proto messages: https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp#Transform
___
*[xds/internal/client/xds.go, line 191 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUG0z8V3X_R1f9VWBEz:-MUG0z8V3X_R1f9VWBF-:b4e571d) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/client/xds.go#L191)):*
> ```Go
> 		name := filter.GetName()
> 		if name == "" {
> 			return nil, errors.New("filter missing name field")
> ```

Also print the `filter`?


<!-- Sent from Reviewable.io -->

2021-02-24 00:03 UTC, menghanl requested changes
> Reviewed 5 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4206)* status: all files reviewed, 15 unresolved discussions (waiting on @dfawley)

___
*[xds/internal/resolver/serviceconfig.go, line 193 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUGKsI82zRJW4gx9PUQ:-MUGKsI82zRJW4gx9PUR:b-6z2le) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/resolver/serviceconfig.go#L193)):*
> ```Go
> 			// Ignore any filters after the router filter.  The router itself
> 			// is currently a nop.
> 			break
> ```

Error here, instead of having a magic fail filter at the end of the list
___
*[xds/internal/resolver/serviceconfig.go, line 276 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUGGX2f9JhmxmuroH8V:-MUGGX2f9JhmxmuroH8W:b-aa5kpy) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/resolver/serviceconfig.go#L276)):*
> ```Go
> 			}
> 			cs.clusters[cluster] = ci
> 			cs.routes[i].clusterHFCO[cluster] = wc.HTTPFilterConfigOverride
> ```

Add this `override` to clusters, instead of a separate map?
___
*[xds/internal/resolver/serviceconfig.go, line 329 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUGIN1k5fA_kroR5tEp:-MUGIN1k5fA_kroR5tEq:b-5r8jas) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/resolver/serviceconfig.go#L329)):*
> ```Go
> }
> 
> func (il *interceptorList) Done() {
> ```

What's this method for?
Interceptor doesn't need a `Done`.


<!-- Sent from Reviewable.io -->

2021-02-24 21:15 UTC, dfawley commented
> Error here, instead of having a magic fail filter at the end of the list

Done

> Add this override to clusters, instead of a separate map?

Good idea. Done.

> What's this method for? Interceptor doesn't need a Done.

Good question.  Done.

2021-02-24 22:09 UTC, menghanl approved these changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc-go/4206)* status: all files reviewed, 2 unresolved discussions (waiting on @dfawley)

___
*[xds/internal/client/lds_test.go, line 419 at r2](https://reviewable.io/reviews/grpc/grpc-go/4206#-MUG6TgA5OHQR7M5GBxv:-MUL3Q5Y6oZXbCdSTzdh:b31m84s) ([raw file](https://github.com/grpc/grpc-go/blob/fb2abc8cecde577f4479811a5f9551fec7ec65cf/xds/internal/client/lds_test.go#L419)):*
<details><summary><i>Previously, menghanl (Menghan Li) wrote…</i></summary><blockquote>

This handles all proto messages: https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp#Transform
</blockquote></details>

How about this? You don't need to add a transformer for each new proto type.


<!-- Sent from Reviewable.io -->

2021-02-25 21:11 UTC, dfawley commented
> How about this? 

Done

2021-02-25 22:04 UTC, merged