Added a GOAWAY frame send on client transport shutdown
grpc/grpc-go pull request #4248
Opened 2021-03-06 16:39 UTC by zasweq

Fixes issue https://github.com/grpc/grpc-go/issues/460. The data of the GOAWAY frame is that of a peer attempting a graceful shutdown according to the HTTP/2 spec (ErrCodeNo, Stream ID of 2 ^ 32 - 1). Eventually, seen by Doug's comment in #4190, it is desirable to pass an error into http2_client.close(), which will end up in the GOAWAY frame, but for now any GOAWAY frame sent is better than none.

2021-03-09 21:36 UTC, dfawley requested changes
Please check the test failures; I suspect they are real errors.

2021-03-09 21:36 UTC, dfawley commented on internal/transport/http2_client.go
> +	if err := t.framer.fr.WriteGoAway(math.MaxUint32, http2.ErrCodeNo, []byte{}); err != nil {
If writing the GOAWAY fails, we still need to close the conn and do the other cleanup below, like adding an error to any streams that are still open.

2021-03-09 21:36 UTC, dfawley commented on internal/transport/http2_client.go
> +	if err := t.framer.fr.WriteGoAway(math.MaxUint32, http2.ErrCodeNo, []byte{}); err != nil {
It's possible we want to do some refactoring here.  I think I was expecting we'd pass an `error` to `http2Client.Close`, and that would dictate the code used here -- OR, pass the code in directly.  Anywhere we already send a GOAWAY, we could delete that and rely on this to do it instead.  Or we need a way to call `Close` to indicate a GOAWAY was already sent, and so `Close` should not send another one.

2021-03-11 21:48 UTC, menghanl commented
Closing this PR now. Let's get back to this when it's ready.

2021-03-11 21:48 UTC, closed without merging