balancer: Fix base balancer set nil attributes into readySCs
grpc/grpc-go pull request #4253
Opened 2021-03-09 09:04 UTC by longXboy

#4024 This PR will cause the Addresses.Attributes obtained by pickerBuilder to be nil when regeneratePicker.

1.add subConnInfo struct which contains subConn and attributes.

2.add attributes to aNoAttrs when generate readySCs.
@menghanl

2021-03-18 18:06 UTC, menghanl requested changes
Thanks for the fix. And sorry for the delay.

This fix looks good to me.
Can you add a test to make sure that the pickers can get the attributes?
Thanks!

2021-03-25 14:32 UTC, longXboy commented
> Thanks for the fix. And sorry for the delay.
> 
> This fix looks good to me.
> Can you add a test to make sure that the pickers can get the attributes?
> Thanks!

ok,I will add some tests

2021-03-25 15:28 UTC, longXboy commented
@menghanl  test cases added!

2021-03-25 18:12 UTC, menghanl approved these changes
LGTM. Thanks for the fix!

2021-03-25 18:12 UTC, menghanl commented on balancer/base/balancer_test.go
> +				if !ok || foo != "2233niang" {
:man_facepalming:

2021-03-25 20:08 UTC, merged