xds: enable timeout, circuit breaking, and fault injection by default
grpc/grpc-go pull request #4286
Opened 2021-03-23 21:51 UTC by dfawley

2021-03-23 22:53 UTC, menghanl requested changes

2021-03-23 22:53 UTC, menghanl commented on internal/xds/env/env.go
>  	// enabled, which can be done by setting the environment variable
Update the comment

2021-03-24 15:29 UTC, dfawley commented on internal/xds/env/env.go
>  	// enabled, which can be done by setting the environment variable
Done, thanks!

2021-03-24 17:12 UTC, menghanl approved these changes

2021-03-24 17:20 UTC, merged