internal/transport: do not mask ConnectionError
grpc/grpc-go pull request #4561
Opened 2021-06-22 15:48 UTC by vmg

Hi everyone! PR #4316 introduces a serious breaking change that is not listed in the 1.38.0 release notes: it is no longer possible to gather meaningful information from the errors returned by the client whenever a `GOAWAY` message has been previously received, because the original `ConnectionError` is wrapped with a `fmt.Errorf` that discards all this information. This is, again, a breaking change that affects projects like the Vitess tablet RPC among others.

This PR contains a potential fix for the issue. The commit message is inlined for your convenience:

```
PR #4316 updates the http2Client `Close` method so it can append
additional debug information about prior GOAWAY messages before this
connection was closed.

However, it is not safe to do this in the general case, as the original
error is propagated through the connection's `Stream` via a `recvMsg`,
and read later on. If the additional metadata is appended by wrapping
the error with `fmt.Errorf`, downstream clients will not be able to
detect meaningful error conditions (such as `io.EOF`) or the temporarity
of the error.

Fix this by properly wrapping the original error with `connectionErrorf`
like it is done for all the other errors in the client.
```

I hope you deem this fix acceptable; if you believe there is a more elegant to maintain the behavior from 1.37.0 please let me know so I can adjust it accordingly.

Thank you,
vmg

2021-06-22 16:31 UTC, dfawley commented
@vmg can you describe more directly what _application-level_ operations are impacted by this: what behavior were you seeing before and what are you seeing now?

2021-06-22 16:37 UTC, vmg commented
@dfawley: not particularly well, no. This was so complex to debug that I only managed to find the issue by running `git bisect` to land on the relevant commit. My assumption is that the `etcd` client that Vitess was using (https://github.com/etcd-io/etcd) was checking the return error from the GRPC client and expecting it to be a `grpc.ConnectionError`, so it could compare its `Origin` against e.g. `io.EOF`. When the original commit in https://github.com/grpc/grpc-go/pull/4316 was merged, **we would see the Vitess instances hanging forever whenever the `etcd` server had a non-clean termination**. With this fix, the Vitess instances can detect that the GRPC connection to `etcd` goes away after the server dies.

2021-06-22 17:33 UTC, dfawley commented
> My assumption is that the etcd client that Vitess was using (etcd-io/etcd) was checking the return error from the GRPC client and expecting it to be a grpc.ConnectionError

There _is_ no `grpc.ConnectionError` type.  The `ConnectionError` type is inside our `internal` transport.  We always convert to `status.Status` errors from RPCs, which is where this would manifest, but I'm not sure exactly how.  Did the status code change?  Are they inspecting our error strings?  I would really like to understand this situation better before deciding on a fix.

2021-06-23 09:01 UTC, vmg commented
>  I would really like to understand this situation better before deciding on a fix.

The change happens in `stream.go`:

https://github.com/grpc/grpc-go/blob/4440c3b8306d28f4af5833bdf12ac54866dc1423/stream.go#L959-L968

The `err` returned from `recv` has been propagated from the `recvBuffer` in the `Stream` for the connection, and is being converted into a `status.Error` by calling `toRPCErr`.

Looking at the implementation for `toRPCErr`:

https://github.com/grpc/grpc-go/blob/4440c3b8306d28f4af5833bdf12ac54866dc1423/rpc_util.go#L831-L853

We can see that it explicitly matches on `transport.ConnectionError` to return an error with `codes.Unavailable`. An error returned from the HTTP2 client that has been wrapped with `fmt.Errorf` will instead passthrough all the way and be returned with a `codes.Unknown` status.

We can look at the error handling for streams in the `etcd` client to see why this breaks:

https://github.com/etcd-io/etcd/blob/556447683112b6ccc00b27a1bd0d0a4edc361692/client/v3/client.go#L508-L523

The error check is doing an explicit `ev.Code() != codes.Unavailable`, which is now always true because the status code after wrapping with `fmt.Errorf` is `codes.Unknown`. This causes the `etcd` client to behave erratically and stop retrying the health checks when it normally would.

With this understanding, I believe my fix to be correct!

2021-06-23 21:31 UTC, dfawley requested changes
Thanks for the analysis.  Yes, I believe `Unavailable` would be the correct code for this situation, as it was before.  Could you change this to return a status error instead of a `ConnectionError`, though?

I.e. something like this:
```go
var st *status.Status
if len(goAwayDebugMessage) > 0 {
	st = status.Newf(codes.Unavailable, "closing transport due to: %v, received prior goaway: %v", err, goAwayDebugMessage)
	err = st.Err()
} else {
	st = status.New(codes.Unavailable, err.Error())
}
// Notify ...
for .... {
	t.closeStream(s, err, false, http2.ErrCodeNo, st, nil, false)
}
```

Generally we shouldn't have both `error` and `Status` inputs to `closeStream`, which contributed to this bug.  So if you're at all interested in helping us improve our code, removing that redundancy would be a nice win for us.  But otherwise the above should be sufficient to fix this issue.

2021-06-24 09:23 UTC, vmg commented
> Generally we shouldn't have both error and Status inputs to closeStream, which contributed to this bug. So if you're at all interested in helping us improve our code, removing that redundancy would be a nice win for us. But otherwise the above should be sufficient to fix this issue.

I've tried giving this a go, but I don't quite see how to remove the `err` argument, as sometimes it is special-cased to be `io.EOF`, a specific value that is used throughout the codebase to mark the end of the stream and that cannot be modeled with just a `Status`. Seems like it would be a very deep refactoring.

I've pushed your suggested change though! Works just fine. :+1:

2021-06-25 17:13 UTC, dfawley commented
> Seems like it would be a very deep refactoring.

You're probably right about that.  I think we could go a few different ways to make it work without _completely_ blowing things up, but it would probably be significant no matter what, and really hard to know what would work best if you're not intimately familiar with the code & interactions between the different layers.

2021-06-25 18:21 UTC, dfawley approved these changes

2021-06-28 16:50 UTC, menghanl approved these changes

2021-06-28 16:51 UTC, merged