listener_wrapper: Expose underlying channel in Channel for some testing scenarios.
grpc/grpc-go pull request #4681
Opened 2021-08-18 02:31 UTC by jackwener

### What problem does this PR solve?

Issue Number: #4662

### What is changed and how it works?

What's Changed:

Expose underlying channel in Channel.

### Related changes

None

Side effects

- None

### Release note 

```release-note
None
```

2021-08-18 09:43 UTC, jackwener commented
@easwars PTAL

2021-08-18 17:55 UTC, easwars requested changes
Were you also planning to fix the test mentioned in the original issue description?

2021-08-18 17:55 UTC, easwars commented on internal/testutils/channel.go
> +// Tests which cannot use ReceiveXxx() for whatever reasons can use C to read the values.
Please move the comment to be above the `C` field.

2021-08-19 00:46 UTC, jackwener commented
> Were you also planning to fix the test mentioned in the original issue description?

Yes, it's ok.

2021-09-15 17:50 UTC, easwars commented
> > Were you also planning to fix the test mentioned in the original issue description?
> 
> Yes, it's ok.

Sorry, did you mean to say you were going to fix the test as well? If you planned to do in a separate PR, then it would be better to just do it here.

2021-09-28 05:11 UTC, closed without merging