fix possible blocked send when cancel watch
grpc/grpc-go pull request #5021
Opened 2021-12-01 01:19 UTC by charlesxsh

=== RUN   TestClientWatchEDS
eds_test.go:xxx: timed out when expecting resource ""

-- FAIL: TestClientWatchEDS (2.00s)

FAIL

If we tweak the some selects in TestClientWatchEDS, for example, delay select in UpdateClientConnState for about 1 seconds to `x.grpcUpdate <- &s`, context in test will timeout, cause cancel watch to be triggered. However, not always `xdsC.edsCancelCh` will have receiver. It will make send operation blocked forever. This fix aims to make an unblocking send operation for notifying xdsC.edsCancelCh. 

The following stack is coming from the old version of gRPC. 
```
goroutine 113 [chan send]:
google.golang.org/grpc/internal/testutils.(*Channel).Send(0xc00000e428, 0x0, 0x0)
	/fuzz/target/internal/testutils/channel.go:41 +0xc5
google.golang.org/grpc/xds/internal/testutils/fakeclient.(*Client).WatchEndpoints.func1()
	/fuzz/target/xds/internal/testutils/fakeclient/client.go:181 +0x36
google.golang.org/grpc/xds/internal/balancer/edsbalancer.(*edsxds/internal/balancer/edsbalancer/eds.go:388Balancer).startEndpointsWatch.func2()
	/fuzz/target/ +0x33
google.golang.org/grpc/xds/internal/balancer/edsbalancer.(*edsBalancer).cancelWatch(0xc000218c60)
	/fuzz/target/xds/internal/balancer/edsbalancer/eds.go:401 +0xa2
google.golang.org/grpc/xds/internal/balancer/edsbalancer.(*edsBalancer).run(0xc000218c60)
	/fuzz/target/xds/internal/balancer/edsbalancer/eds.go:283 +0xbcb
created by google.golang.org/grpc/xds/internal/balancer/edsbalancer.(*edsBalancerBuilder).Build
	/fuzz/target/xds/internal/balancer/edsbalancer/eds.go:87 +0x68b
```

2021-12-07 22:01 UTC, dfawley requested changes
This doesn't seem correct to me.  Cancels could get lost if the receiver is slow.  There is already a buffer of 10 entries -- is this not sufficient?

2021-12-14 16:38 UTC, charlesxsh commented
> This doesn't seem correct to me. Cancels could get lost if the receiver is slow. There is already a buffer of 10 entries -- is this not sufficient?

Could you give me a hint where is the buffer of 10 entries?

2021-12-14 16:49 UTC, dfawley commented
> Could you give me a hint where is the buffer of 10 entries?

Line 316 where `edsCancelCh` is initialized.

2021-12-14 22:45 UTC, charlesxsh commented
Then now it should be partially fixed. Since it is found on the old code.

2021-12-20 20:32 UTC, dfawley commented
> Then now it should be partially fixed. Since it is found on the old code.

Can you explain what you mean by "partially"?  Can it still fail?

2022-01-02 20:45 UTC, closed without merging