xds: Added RLS in xDS e2e test.
grpc/grpc-go pull request #5281
Opened 2022-03-29 20:38 UTC by zasweq

This PR adds an RLS in xDS e2e test. This tests that the RLS in xDS functionality works, and correctly configures and uses a RLS Load Balancer. This addresses issue #5216.

RELEASE NOTES: None

2022-03-31 04:45 UTC, easwars requested changes
Wrt to moving code around from `balancer/rls/helpers_test.go` and `balancer/rls/internal/test/e2e/rls_fakeserver.go` to `balancer/rls/test/rls.go`, it seems to be moving stuff out of an `internal` directory into a non-internal directory.

May I suggest the following:
- Types like `ListenerWrapper` and `ConnWrapper` are nothing specific to rls. You might consider moving them to `internal/testutils` package
- Other functionality like spinning up the fake RLS server etc, you might consider moving to some common, but internal directory. Maybe something like `internal/testutils/rls` or `internal/rls/testutils`. The only downside of these two approaches is that it would require import renaming when they are used. But I would prefer that instead of having these in non-internal directories.

2022-03-31 04:45 UTC, easwars commented on xds/internal/clusterspecifier/rls/rls.go
> +// test before init() in this package is run.
Does this mean that we can get rid of this once the env var is removed? If so, could you please add a TODO for the same here.

2022-03-31 04:45 UTC, easwars commented on xds/internal/httpfilter/rbac/rbac.go
> +// in this package is run.
Same here about being able to remove this once the env var is gone. If so, please add TODO.

2022-03-31 04:45 UTC, easwars commented on xds/internal/test/xds_client_integration_test.go
> +	_ "google.golang.org/grpc/balancer/rls"
Please group blank imports in a separate group and add a one line comment for each as to why they are imported. I find that much more readable. Thanks.

2022-03-31 04:45 UTC, easwars commented on xds/internal/test/xds_client_integration_test.go
> +		t.Fatalf("test.LocalTCPListener() failed: %v", err)
Why do we need this change?

2022-03-31 04:45 UTC, easwars commented on xds/internal/testutils/e2e/clientresources.go
> +func DefaultClientResourcesWithRLSCSP(params ResourceParams, rlsProto *rlspb.RouteLookupConfig) UpdateOptions {
Does this function need to live here and be exported? Or can it live as an unexported function in the same package in which the test is defined. I don't foresee other tests needing this.

2022-03-31 04:45 UTC, easwars commented on xds/internal/testutils/e2e/clientresources.go
> +func DefaultRouteConfigWithRLSCSP(routeName, ldsTarget string, rlsProto *rlspb.RouteLookupConfig) *v3routepb.RouteConfiguration {
Same here.

2022-03-31 04:45 UTC, easwars commented on xds/internal/test/xds_client_integration_test.go
> +	defer rlscsp.UnregisterForTesting()
Nit: combine the two statements being deferred into a single defer call?

2022-03-31 04:45 UTC, easwars commented on xds/internal/test/xds_client_integration_test.go
> +	if err != nil {
Please combine these two lines.

2022-03-31 16:40 UTC, zasweq reviewed
Thanks for the comments :D! I originally moved testing helpers to internal/testutils, but there was a cyclic dependency with grpc (the fake RLS Server uses grpc). Your suggestion of moving the Conn/Listener wrappers to internal/testutils and moving the fake RLS Server to internal/testutils/rls fixed this :D!

2022-03-31 22:12 UTC, easwars requested changes

2022-03-31 22:12 UTC, easwars commented on balancer/rls/helpers_test.go
> +// 1. Delete what was present here that I moved to prevent code duplication - then fix balancer test
Please remove this comment.

2022-03-31 22:12 UTC, easwars commented on balancer/rls/picker_test.go
> +	for _, tst := range tests {
No need to rename `test` to `tst` now that the testing package is called `rlstest`.

2022-03-31 22:12 UTC, easwars commented on balancer/rls/picker_test.go
> +	for _, tst := range tests {
Same here. Undo renaming.

2022-03-31 22:12 UTC, easwars commented on balancer/rls/picker_test.go
> +	for _, tst := range tests {
And here. And in all tests below.

2022-03-31 22:12 UTC, easwars commented on internal/testutils/rls/fake_rls_server.go
> +// Package rls contains utilities for RouteLookupService tests.
Package rls contains utilities for RouteLookupService e2e tests?

2022-03-31 22:12 UTC, easwars commented on internal/testutils/rls/fake_rls_server.go
> +	return resp.Resp, resp.Err // Set this target to correspond to correct cluster for RLS to proceed as normal
Are these changes required?

2022-03-31 22:12 UTC, easwars commented on xds/internal/test/xds_client_integration_test.go
> +	_ "google.golang.org/grpc/xds/internal/clusterspecifier/rls"
I meant something like this:

```golang
_ "google.golang.org/grpc/balancer/rls" // Register the RLS Load Balancing policy.
_ "google.golang.org/grpc/xds/internal/clusterspecifier/rls" // Register the RLS Cluster Specifier Plugin.
```

Sorry for the nit.

2022-04-01 00:23 UTC, easwars commented
In https://github.com/grpc/grpc-go/pull/5285, I figured out a way to use the `stubBalancer` to use a real balancer underneath it. Once that is merged, we could get rid of the code in `rls_child_policy.go` and use the former instead.

2022-04-01 15:00 UTC, zasweq reviewed
Thanks for the comments :D! Sorry about all the personal checked in comments. Noted @ your stub balancer comment.

2022-04-01 15:41 UTC, easwars approved these changes

2022-04-04 21:38 UTC, merged