Log xDS bootstrap with verbosity INFO
grpc/grpc-go pull request #5860
Opened 2022-12-13 00:52 UTC by mohanli-ml

Log xDS bootstrap so that we can better debug DirectPath issues.

C++: https://github.com/grpc/grpc/pull/31797
Java: https://github.com/grpc/grpc-java/pull/9731

2022-12-13 18:09 UTC, mohanli-ml commented
From https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/bootstrap/bootstrap.go#L114 the NodeProto can have different type, so I just log the entire bootstrap as a string for simplicity. Please suggest.

2022-12-13 18:26 UTC, dfawley requested changes

2022-12-13 18:26 UTC, dfawley commented on xds/internal/xdsclient/singleton.go
> +	logger.Info("xDS bootstrap: %s", c.BootstrapConfig().XDSServer.NodeProto.String())
This should work:

```go
nodeID := "<unknown>"
if id, ok := config.XDSServer.NodeProto.(interface { GetId() string }); ok {
  nodeID = id.GetId()
}
logger.Infof("xds: node ID: %s", nodeID)
```

2022-12-13 19:35 UTC, mohanli-ml commented on xds/internal/xdsclient/singleton.go
> +	logger.Info("xDS bootstrap: %s", c.BootstrapConfig().XDSServer.NodeProto.String())
Done. Thanks!

2022-12-14 17:05 UTC, dfawley approved these changes

2022-12-14 17:05 UTC, merged