Advancedtls cipher suites
grpc/grpc-go pull request #6007
Opened 2023-02-04 16:58 UTC by joeljeske

(Continuation of #5797 cc @ZhenLian)

Adding an "TlsVersionOption" for users to select their desired min/max TLS versions, if advanced TLS is used, per request by https://github.com/grpc/grpc-go/issues/5667

RELEASE NOTES:

security/advancedtls: add min/max TLS version selection options

2023-02-11 00:55 UTC, ZhenLian commented
I am OOO right now... Adding @erm-g to take a look, thanks!

2023-02-21 18:47 UTC, zasweq commented
@erm-g can you please take a look at this?

2023-02-21 20:10 UTC, erm-g commented
Hi @dfawley ,
Could you take a look at comment by Zhen https://github.com/grpc/grpc-go/issues/5667#issuecomment-1297846392 ?
Actually, from my perspective it's a good idea to expose `tls.Config` for kind of 'power users'. Does this pattern make sense for you?

2023-03-07 22:21 UTC, dfawley commented
> Could you take a look at comment by Zhen #5667 (comment) ?
> Actually, from my perspective it's a good idea to expose tls.Config for kind of 'power users'. Does this pattern make sense for you?

I have no strong feelings here one way or anything.  I'll leave it up to the security team to define the API here.  If you think users will need direct interaction with `tls.Config` then that's fine, just keep in mind that we provide base-level access to that via our [base TLS credentials](https://pkg.go.dev/google.golang.org/grpc/credentials#NewTLS).

2023-03-14 16:07 UTC, easwars commented
Another gentle ping @erm-g

2023-03-28 20:08 UTC, erm-g requested changes
@joeljeske We had an internal discussion and can merge this PR. Please keep in mind that, in the long term, we will be exposing 'tls.Config' and signatures may change. This API is still in an experimental stage.
I see there are some failing tests - once it's fix I can merge the PR.

2023-04-10 17:05 UTC, easwars commented
@erm-g : Looks like you requested changes, but never approved the PR. Could you please approve it, and I can merge it. Thanks.

2023-04-10 18:12 UTC, erm-g approved these changes
Approved

2023-04-10 19:27 UTC, merged