Upgrade golang.org/x/net to v0.7.0
grpc/grpc-go pull request #6038
Opened 2023-02-20 09:18 UTC by xaxes

Upgrades golang.org/x/net and some other dependencies due to CVE-2022-41723.

2023-02-22 00:48 UTC, zasweq requested changes

2023-02-22 00:48 UTC, zasweq commented on examples/go.mod
> +	golang.org/x/net v0.7.0 // indirect
I see the vulnerability from this, but why are we upgrading the other /sys /text dependencies across the codebase?

2023-02-22 02:21 UTC, easwars commented
@xaxes : Could you please sign the SLA.

2023-02-28 03:09 UTC, easwars commented
@dfawley: The author of this PR has not replied from the time they sent this PR. Should we make a new PR to ensure that these changes are made in time for the 1.54 release?

2023-03-07 17:21 UTC, dfawley commented
Yes, we should do this on our own.

2023-03-07 17:21 UTC, closed without merging