stats/opencensus: New uncompressed metrics and align with tracing spec
grpc/grpc-go pull request #6051
Opened 2023-02-23 23:55 UTC by zasweq

This PR does a few things:
* Fixes the docstrings (the docstrings for WireLength In and Out Payload were incorrect with respect to what they were recording) of InPayload and OutPayload
* Adds a new field (don't change WireLength to not break users) that records the compressed bytes of a message, not including gRPC framing bytes (1 byte compressed flag and 4 byte message length), and transport framing bytes (HTTP/2 framing headers and padding length byte if applicable and padding)
* Uses this new field to record new client and server uncompressed bytes sent/recv metrics
* Uses this new field instead of the previously used WireLength to align with the tracing specs language: "Compressed bytes: Total bytes (compressed) [sent/received] per message; does omit grpc and transport framing bytes."

2023-03-02 17:57 UTC, dfawley requested changes
Mostly LGTM, just a question to improve the tests & comments about comments.

2023-03-02 17:57 UTC, dfawley commented on stats/stats.go
> +	// WireLength is the length of tbe compressed data, alongside gRPC framing
*the

2023-03-02 22:16 UTC, zasweq commented on stats/stats.go
> +	// WireLength is the length of tbe compressed data, alongside gRPC framing
Whoops. Switched.

2023-03-02 22:18 UTC, zasweq commented on stats/stats.go
> +	CompressedLength int
Yes, is zero. See gRPC-Go chat for reasonings/back and forth. Will specify. Changed to your first suggestion. I will specify in parentheses after any framing (gRPC or HTTP) just to be clear.

2023-03-03 01:25 UTC, zasweq commented on stats/opencensus/e2e_test.go
> +							CountPerBucket: []int64{1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
Done. Enabled gzip compression, sent a 10k byte payload (only in Unary). Only touched compressed/uncompressed bytes sent/received metrics (no other assertions were affected), which is exactly what we wanted.

2023-03-03 22:14 UTC, dfawley approved these changes

2023-03-03 22:21 UTC, merged