Add logger to outlierDetection LB
grpc/grpc-go pull request #6145
Opened 2023-03-22 22:05 UTC by s-matyukevich

This PR replicates https://github.com/grpc/grpc-java/pull/9880 from grpc-java, which adds additional logging to the outlierDetection LB to improve observability.

Here are the additional messages that will be logged (taken from my end-to-end test):

```
2023-03-22T21:42:53.659526+00:00 DEBUG (outlierdetection/balancer.go:852) - [xds] [Channel #1] FailurePercentage algorithm detected outlier: [[{
  "Addr": "10.135.22.187:3000",
  "ServerName": "",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null 
}]], failurePercentage=100.000000
```
And a similar message for the success rate algorithm

```
2023-03-22T21:42:53.659588+00:00 DEBUG (outlierdetection/balancer.go:868) - [xds] [Channel #1] Subchannel ejected: [{
  "Addr": "10.135.22.187:3000",
  "ServerName": "",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null 
}]
```
And a similar message for the unejection event.

It would be nice to use sub-channel logger, but this would require passing sub-channel channelz ID to the balancer, which is currently not possible and requires changing `SubConn` interface.

2023-03-23 08:38 UTC, atollena commented on xds/internal/balancer/outlierdetection/balancer.go
> +		channelz.Infof(logger, b.channelzParentID, "Subchannel ejected: %+v", sbw.string())
nit: it's a string so you can simply use `%s`.

2023-03-23 08:38 UTC, atollena commented on xds/internal/balancer/outlierdetection/balancer.go
> +		channelz.Infof(logger, b.channelzParentID, "Subchannel unejected: %+v", sbw.string())
same comment about using `%s`.

2023-03-23 08:39 UTC, atollena commented
cc @zasweq

2023-04-11 16:14 UTC, s-matyukevich commented
@zasweq Any updates on this?

2023-04-11 18:54 UTC, zasweq commented
Taking a look now. Sorry for the delay.

2023-04-11 21:06 UTC, zasweq requested changes
Thanks for the contribution. Sorry for the late pass.

2023-04-11 21:06 UTC, zasweq commented on xds/internal/balancer/outlierdetection/balancer.go
> +		channelzParentID: bOpts.ChannelzParentID,
Is this the right name of the variable here? There is no concept of nested Client Conns here, as the documentation for this Dial Option (not a Balancer Option) states: https://github.com/grpc/grpc-go/blob/81b30924fc44b3b7ecc77a4da763fc462f94e98e/dialoptions.go#L544

2023-04-25 17:17 UTC, zasweq approved these changes
LGTM. Thanks for the contribution!

2023-04-25 17:17 UTC, merged

2023-04-25 17:26 UTC, dfawley reviewed
LGTM; @zasweq will follow-up to see if string() should be changed to String()