status: fix issue #6667 Panic on nil pointer dereference
grpc/grpc-go pull request #6730
Opened 2023-10-15 08:56 UTC by JalajGoswami

**Description:**
This pull request resolves issue #6667 "Panic (nil pointer dereference) in processStreamingRPC". This change ensures that the program does not crash due to a nil pointer dereference.

**Changes Made:**
- Added nil checks in FromError function of status package.

**Testing Done:**
- To test this change, I ran the status_test.go.

2023-10-16 18:48 UTC, arvindbr8 requested changes

2023-10-16 18:48 UTC, arvindbr8 commented on status/status.go
>  		if grpcStatus == nil {
I would squash this into a short circuit conditional check like this
```suggestion
		if gs == nil || gs.GRPCStatus() == nil {
```

2023-10-16 18:48 UTC, arvindbr8 commented on status/status.go
>  		if grpcStatus == nil {
Same here 
```suggestion
		if gs == nil || gs.GRPCStatus() == nil {
```

2023-10-16 18:48 UTC, arvindbr8 commented on status/status.go
If you go with my comment, `codecov` might not complain about diff coverage. However, I would recommend adding a condition that forces the condition where `gs == nil`

2023-10-16 21:12 UTC, arvindbr8 commented
`Testing / tests: vet` failed due to the typo.

2023-10-17 07:08 UTC, closed without merging

2023-10-17 07:11 UTC, JalajGoswami commented
Thanks @arvindbr8 for your help, I'm applying the changes you suggested & creating a fresh pr