xds/internal/server: Fix nil panic in Listener Wrapper
grpc/grpc-go pull request #6747
Opened 2023-10-24 23:42 UTC by zasweq

This PR fixes a nil panic in Listener Wrapper, from a nil receiver described in issue #6683.

RELEASE NOTES:
* xds/internal/server: Fix nil panic in Listener Wrapper

2023-10-25 20:13 UTC, dfawley reviewed
Code changes LGTM except for the stray comment, but I think you said we'll need to patch this on the release branch, but it's different from main.

More importantly: for this PR, can you write a test that reproduces this, confirms this fixes it, and helps us write the fix on the release branch?

Thanks!

2023-10-25 20:13 UTC, dfawley commented on xds/internal/server/listener_wrapper_test.go
> +func (s) TestListenerWrapper_RouteNames(t *testing.T) { // This is what I need, LDS + RDS and then accept a conn that looks up
Remove

2023-10-31 00:40 UTC, zasweq commented on xds/internal/server/listener_wrapper_test.go
> +func (s) TestListenerWrapper_RouteNames(t *testing.T) { // This is what I need, LDS + RDS and then accept a conn that looks up
Whoops, done.

2023-10-31 00:40 UTC, zasweq commented
Added a test which triggers nil panic on master, and the fix fixes it. Will work on release branches now.

2023-10-31 00:55 UTC, zasweq commented
Added a test which triggers it on master and verifies fix.

2023-10-31 20:54 UTC, dfawley approved these changes

2023-10-31 20:54 UTC, dfawley commented on test/xds/xds_server_test.go
> +	modeChangeOpt := xds.ServingModeCallback(func(addr net.Addr, args xds.ServingModeChangeArgs) {
Please add a comment as mentioned.

2023-10-31 21:53 UTC, dfawley requested changes
Some comments as we discussed offline

2023-10-31 21:53 UTC, dfawley commented on xds/internal/server/listener_wrapper.go
> +			l.filterChains = nil
This is wrong; we should not throw away the LDS data when we get a bad RDS.  A good RDS needs to be able to work again.

2023-10-31 21:53 UTC, dfawley commented on xds/internal/server/listener_wrapper.go
>  	atomic.StorePointer(&l.rdsUpdates, unsafe.Pointer(&update.updates))
We need to verify somewhere that we are still watching this RDS update.  Probably at the top?

2023-10-31 21:53 UTC, dfawley commented on xds/internal/server/listener_wrapper.go
> +		l.switchModeLocked(connectivity.ServingModeNotServing, fmt.Errorf("address (%s:%s) in Listener update does not match listening address: (%s:%s)", ilc.Address, ilc.Port, l.addr, l.port))
This also needs to stop the RDS watch if there was one, such that subsequent RDS updates are ignored.

2023-10-31 21:56 UTC, zasweq commented on test/xds/xds_server_test.go
> +	modeChangeOpt := xds.ServingModeCallback(func(addr net.Addr, args xds.ServingModeChangeArgs) {
Added a comment.

2023-11-03 15:56 UTC, dfawley commented
I'll just close this since I think there's even more to it than we were originally thinking.

2023-11-03 15:56 UTC, closed without merging