resolver: manual resolver crashes if grpc.Dial isn't called before some methods
grpc/grpc-go pull request #6754
Opened 2023-10-30 02:27 UTC by henvic

### What version of gRPC are you using?
1.59.0

### What version of Go are you using (`go version`)?
1.21.3

### What operating system (Linux, Windows, …) and version?
macOS Sonoma

### What did you do?
I tried to update the state on a manual resolver before associating it to a *grpc.ClientConn (calling grpc.Dial).

### What did you expect to see?
Panic message should be straight-forward.

### What did you see instead?
I've got a cryptic panic.

2023-10-31 18:13 UTC, dfawley commented on resolver/manual/manual.go
> +		r.mu.Unlock()
As above re: `defer` except there is no concern about callbacks in this case.

2023-11-06 22:51 UTC, dfawley approved these changes
LGTM modulo the date thing.  Thanks!

2023-11-06 22:51 UTC, dfawley commented on resolver/manual/manual_test.go
> + * Copyright 2017 gRPC authors.
Please update to 2023.

2023-11-06 22:51 UTC, dfawley commented
@arvindbr8 PTAL; thanks!

2023-11-06 23:03 UTC, arvindbr8 requested changes

2023-11-06 23:03 UTC, arvindbr8 commented on resolver/manual/manual_test.go
> +	t.Run("update_state", func(t *testing.T) {
I would prefer if the sub test description said not just `update_state`. This subtest asserts the panic message when updateState fails. So maybe something like 

```suggestion
	t.Run("update_state_panics", func(t *testing.T) {
```

2023-11-06 23:03 UTC, arvindbr8 commented on resolver/manual/manual_test.go
> +	t.Run("report_error", func(t *testing.T) {
Similarly for `report_error`

2023-11-06 23:03 UTC, arvindbr8 commented on resolver/manual/manual_test.go
> +	_, err := grpc.Dial("whatever://localhost",
This seems like another subTest to me. I would prefer if we did this also inside of a `t.Run("happy path", func(t *testing.T)`

2023-11-07 19:15 UTC, arvindbr8 approved these changes

2023-11-07 21:09 UTC, merged