removing Roots deprecated Subjects field in tests
grpc/grpc-go pull request #6907
Opened 2024-01-04 21:50 UTC by zedGGs

Regarding this issue: 
https://github.com/grpc/grpc-go/issues/6782,

one of the goals was to remove usage of deprecated field Subjects, which is not being returned by SystemCertPool anymore

also I have updated this tests so we compare got and wanted CertPool structs

2024-01-05 19:35 UTC, arvindbr8 approved these changes
LGTM. Thanks for the PR. We need another maintainer's review before we can check this in. cc: @ginayeh could you please take a look at this?

2024-01-05 20:04 UTC, zedGGs commented
Heey @arvindbr8 , thanks for reply, as I see everyone is on vacation and you are in charge now hehe, cheers ! 
btw I can also update comments in tests

2024-01-08 07:34 UTC, zedGGs commented
@arvindbr8 , I had just removed unneeded comments, where `Subjects` are mentioned, that are not used anymore
and `cmp` that is not used anymore,

I suppose there's no need for comments since its obvious from `Equal` what are we doing, similar to code above in same files, where `Equal` is only used without additional explanation, 

I can still update and change this if you want

2024-01-08 22:59 UTC, arvindbr8 requested changes
Thanks! The updates made to the comments LGTM

However, I think we remove corresponding ignores of those usages in [vet.sh]( github.com/grpc/grpc-go/blob/master/vet.sh#L190). Could you please append your PR with that?

2024-01-08 23:06 UTC, arvindbr8 commented
Marking this PR as fixing #6782 since the other half of the issue was already fixed by you @zedGGs

2024-01-10 00:27 UTC, zedGGs commented
@arvindbr8 I have updated pr, but not sure is this still okey ? since vet-proto is not good

2024-01-10 23:48 UTC, arvindbr8 requested changes
Overall the changes looks good to me.  Please address that one comment about the `pb.go` file

> btw I added small update on vet-proto

We should not be doing that as part of this change. I have actually merged a change to update the `pb.go` file. Please rollback that file and rebase from master -- and vet-proto should be happy :)

2024-01-10 23:48 UTC, arvindbr8 commented on binarylog/grpc_binarylog_v1/binarylog.pb.go
Please roll this back

2024-01-12 05:25 UTC, zedGGs commented on binarylog/grpc_binarylog_v1/binarylog.pb.go
thank you for the reivew, I have updated pr but tests seems not to pass Im not sure is that because of flakines with xds tests 

I apologise, I have managed somehow to have push from wrong account, I 
if this matters I can add separated pr for this

2024-01-12 17:30 UTC, arvindbr8 approved these changes

2024-01-12 17:31 UTC, arvindbr8 commented
Thanks, this looks good to me. cc'ing @ginayeh for a second pass

2024-01-16 23:22 UTC, ginayeh approved these changes

2024-01-16 23:24 UTC, merged