Update docs and examples and tests to use NewClient instead of Dial
grpc/grpc-go pull request #7068
Opened 2024-03-29 12:31 UTC by silaselisha

- [x] refactored tests and examples that utilized `grpc.Dial` to `grpc.NewClient` while some tests were left to use the deprecated `grpc.Dial`

2024-03-29 21:38 UTC, arvindbr8 commented
Nice work on the PR. Thanks for taking a look at this. However while grep-ing, I still see more usages of `grpc.Dial`. I think we should probably add all of that as part of this patchset

<details>
<summary>grep output</summary>

```
./Documentation/encoding.md:	myclient := grpc.Dial(ctx, target, grpc.WithDefaultCallOptions(grpc.CallContentSubtype("mycodec")))
./Documentation/encoding.md:	myclient := grpc.Dial(ctx, target, grpc.WithDefaultCallOptions(grpc.UseCompressor("gzip")))
./Documentation/grpc-auth-support.md:conn, err := grpc.Dial(serverAddr, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")))
./Documentation/grpc-auth-support.md:conn, err := grpc.Dial(serverAddr, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")), grpc.WithPerRPCCredentials(oauth.NewComputeEngine()))
./Documentation/grpc-auth-support.md:conn, err := grpc.Dial(serverAddr, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")), grpc.WithPerRPCCredentials(jwtCreds))
./resolver_balancer_ext_test.go:	cc, err := grpc.Dial(name+":///", grpc.WithTransportCredentials(insecure.NewCredentials()))
./resolver_balancer_ext_test.go:	cc, err := grpc.Dial(name+":///", grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/local_creds_test.go:		cc, err = grpc.Dial(lisAddr, grpc.WithTransportCredentials(local.NewCredentials()), grpc.WithContextDialer(
./test/creds_test.go:	cc, err := grpc.Dial(r.Scheme()+":///"+testAuthority, grpc.WithTransportCredentials(cred), grpc.WithResolvers(r))
./test/creds_test.go:	cc, err := grpc.Dial(r.Scheme()+":///"+testAuthority, grpc.WithTransportCredentials(cred), grpc.WithResolvers(r))
./test/creds_test.go:	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(cred))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(target, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(target, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(target, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/balancer_switching_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/goaway_test.go:	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/clientconn_state_transition_test.go:	client, err := grpc.Dial("",
./test/clientconn_state_transition_test.go:	client, err := grpc.Dial(lis.Addr().String(),
./test/clientconn_state_transition_test.go:	client, err := grpc.Dial("whatever:///this-gets-overwritten",
./test/clientconn_state_transition_test.go:	client, err := grpc.Dial("whatever:///this-gets-overwritten",
./test/clientconn_state_transition_test.go:	cc, err := grpc.Dial(testResName+":///",
./test/authority_test.go:	cc, err := grpc.Dial(":"+port, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithContextDialer(func(ctx context.Context, addr string) (net.Conn, error) {
./test/roundrobin_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./test/pickfirst_test.go:	cc, err := grpc.Dial(lis.Addr().String(), dopts...)
./test/pickfirst_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./test/pickfirst_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./test/end2end_test.go:	te.cc, err = grpc.Dial(scheme+te.srvAddr, opts...)
./test/end2end_test.go:	te.cc, err = grpc.Dial(scheme+te.srvAddr, opts...)
./test/end2end_test.go:	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/end2end_test.go:	cc, err := grpc.Dial("passthrough:///"+lis.Addr().String(), grpc.WithTransportCredentials(&clientFailCreds{}))
./test/end2end_test.go:	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/end2end_test.go:	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/end2end_test.go:	cc, err := grpc.Dial(mr.Scheme()+":///", grpc.WithResolvers(mr), grpc.WithStatsHandler(sh), grpc.WithTransportCredentials(insecure.NewCredentials()))
./test/healthcheck_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", opts...)
./test/xds/xds_client_federation_test.go:	_, err = grpc.Dial(target, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(resolver))
./test/xds/xds_client_certificate_providers_test.go:	cc, err := grpc.Dial(fmt.Sprintf("xds:///%s", serviceName), grpc.WithTransportCredentials(creds), grpc.WithResolvers(resolverBuilder))
./test/resolver_update_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./test/resolver_update_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithResolvers(r))
./dialoptions.go:// security is incompatible and will cause grpc.Dial() to fail.
./interop/grpclb_fallback/client_linux.go:	conn, err := grpc.Dial(*serverURI, opts...)
./interop/test_utils.go:		conn, err = grpc.Dial(serverAddr, dopts...)
./interop/observability/client/client.go:	conn, err := grpc.Dial(serverAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
./interop/http2/negative_http2_client.go:	conn, err := grpc.Dial(serverAddr, opts...)
./interop/alts/client/client.go:	conn, err := grpc.Dial(*serverAddr, grpc.WithTransportCredentials(altsTC), grpc.WithBlock())
./interop/xds_federation/client.go:		cc, err := grpc.Dial(uris[i], opts...)
./interop/xds/client/client.go:		conn, err := grpc.Dial(*server, grpc.WithTransportCredentials(creds))
./interop/client/client.go:	conn, err := grpc.Dial(serverAddr, opts...)
./interop/stress/metrics_client/main.go:	conn, err := grpc.Dial(*metricsServerAddress, grpc.WithTransportCredentials(insecure.NewCredentials()))
./interop/stress/client/main.go:	return grpc.Dial(address, opts...)
./admin/test/utils.go:	conn, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
./internal/idle/idle_e2e_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./internal/idle/idle_e2e_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./internal/idle/idle_e2e_test.go:			cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./internal/idle/idle_e2e_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./internal/idle/idle_e2e_test.go:	cc, err := grpc.Dial(r.Scheme()+":///test.server", dopts...)
./internal/stubserver/stubserver.go:	cc, err := grpc.Dial(ss.Target, opts...)
./balancer/rls/control_channel.go:	ctrlCh.cc, err = grpc.Dial(rlsServerName, dopts...)
./balancer/rls/balancer_test.go:	cc, err := grpc.Dial(r.Scheme()+":///", grpc.WithResolvers(r), grpc.WithTransportCredentials(insecure.NewCredentials()))
./balancer/rls/balancer_test.go:	cc, err := grpc.Dial(r.Scheme()+":///rls.test.example.com", grpc.WithResolvers(r), grpc.WithTransportCredentials(clientCreds))
./balancer/rls/balancer_test.go:	cc, err := grpc.Dial(r.Scheme()+":///rls.test.example.com", grpc.WithResolvers(r), grpc.WithTransportCredentials(insecure.NewCredentials()))
./balancer/rls/balancer_test.go:	cc, err := grpc.Dial(r.Scheme()+":///", grpc.WithResolvers(r), grpc.WithTr [...]

2024-04-02 06:41 UTC, silaselisha commented
@arvindbr8 a polite request for clarity on `Testing, Attempt #2 / tests (extras, 1.22)`  failing. I'll be more than happy to redo the task.

2024-04-02 20:38 UTC, arvindbr8 commented
@silaselisha -- Thanks for bringing that issue to our notice. Seems like there is a bug in NewClient that is causing a regression. Investigating it [here](https://github.com/grpc/grpc-go/issues/7075)

2024-04-02 20:38 UTC, arvindbr8 commented
But that shouldn't necessarily block your PR

2024-04-02 20:59 UTC, silaselisha commented
@arvindbr8 I'll look into issue your raised, to learn the dynamics of the `grpc.NewClient`

2024-04-02 21:51 UTC, arvindbr8 commented
I turned up the logs with `GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99` and noticed that the orcaLB that is passed in the test is asserting that the `len(addrs) == 1` here: https://github.com/grpc/grpc-go/blob/4ec8307379292dcbe4105ef65d6f9d1f569aa87d/examples/features/orca/client/main.go#L103-L106


In the case of the Github VM (and in my local machine) the dns resolver returned both the ipv6 and ipv4 address.

It's unclear why we need that since the example should work even if there are more addresses. I would just remove that conditional in `UpdateClientConnState` method in orcaLB

2024-04-02 22:36 UTC, silaselisha commented
@arvindbr8 if both ipv4 and ipv6 are returned, is it possible to just change the condition to `len(addrs) != 2`? And are there instances where one `ip` version will be expected?

2024-04-02 22:38 UTC, arvindbr8 commented
Its not deterministic because it depends on the machine you run the test in and the ENI(s) configured. I would just get rid of the conditional there.

2024-04-02 22:46 UTC, silaselisha commented
@arvindbr8 since `grpc.DialWithContext` is deprecated too, will it be right for it to be part of this PR?

2024-04-02 23:15 UTC, arvindbr8 commented
Sure. I'm also okay even if we decide to do this in increments.

2024-04-10 14:05 UTC, silaselisha commented
@arvindbr8 a polite request you review this issue here.

2024-04-10 21:44 UTC, arvindbr8 commented
@silaselisha -- Seems like maybe you didnt push your branch to remote? I'm not seeing a new commit after the last review. I'm particular about this [comment](https://github.com/grpc/grpc-go/pull/7068#issuecomment-2033167289) which would help satisfy Testing (extras) /orca example

2024-04-10 22:23 UTC, silaselisha commented
@arvindbr8 in reference to a closed issue #7075 that you had created to fix Testing (extras) /orca example.

2024-04-10 22:26 UTC, silaselisha commented
> I turned up the logs with `GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99` and noticed that the orcaLB that is passed in the test is asserting that the `len(addrs) == 1` here:
> 
> https://github.com/grpc/grpc-go/blob/4ec8307379292dcbe4105ef65d6f9d1f569aa87d/examples/features/orca/client/main.go#L103-L106
> 
> In the case of the Github VM (and in my local machine) the dns resolver returned both the ipv6 and ipv4 address.
> 
> It's unclear why we need that since the example should work even if there are more addresses. I would just remove that conditional in `UpdateClientConnState` method in orcaLB

I would also like to refer you to this comment.

2024-04-10 22:33 UTC, arvindbr8 commented
I closed #7075 because the error was with the way the test was setup. We shouldnt ideally be expecting the resolver to only return 1 address. That's why I mentioned in the [comment](https://github.com/grpc/grpc-go/pull/7068#issuecomment-2033167289) that the fix for the test can be along with this PR. 

Ideally @dfawley mentioned how he would like to split the update in #7049. Your PR seems like it does tackle most of (1) and (2). This is better for tracking. 

If you don't prefer to do that, you can revert your changes to `examples/` and someone else could pick up that piece.

2024-04-10 22:41 UTC, silaselisha commented
I don't mind including that piece in this PR, I am working on the missing piece, and I'll push the changes asp.

2024-04-15 10:04 UTC, silaselisha commented
@arvindbr8 I mad the necessary changes but I now the PR it has more unnecessary commits

2024-04-15 15:36 UTC, dfawley commented
Something is wrong with your fork's git repo, apparently.  If you can't figure it out, worst case: you can make a new directory and (assuming `upstream` is `github.com/grpc/grpc-go`): `get fetch upstream; git reset --hard upstream/master`, then `cp -rf` from the old directory into the new directory.

2024-04-15 22:23 UTC, arvindbr8 requested changes

2024-04-15 22:23 UTC, arvindbr8 commented on examples/features/orca/client/main.go
> +	// }
nix these lines instead of comment? 

```suggestion
```

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +[`WithBlock`](https://pkg.go.dev/google.golang.org/grpc#WithBlock) in an instance where WithBlock(true) is used, `Connect` and `WaitForStateChange` is invoked until either the context created via `co
Do we need to add this here since `WithBlock` is deprecated, and is not available in NewClient?

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +### Difference between Dial and NewClient
I would prefer changing the content under `### Dialing in gRPC` to talk about `NewClient` and swap the current content under the heading over here.

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +[`grpc.NewClient`](https://pkg.go.dev/google.golang.org/grpc#NewClient) is a function in the grpc libaray that creates a new gRPC `channel` for the target URI that is passed in as an argument, togeth
please line wrap to 80 cols. Applies to all the changes in this file.

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +`grpc.NewClient` uses passthrough as the default name resolver for backward compatibility while  `Dial` uses dns as its default name resolver. This subtle diffrence is crucial in legacy systems that
```suggestion
`grpc.NewClient` uses passthrough as the default name resolver for backward compatibility while  `Dial` uses dns as its default name resolver. This subtle difference is crucial in legacy systems that specify a custom dialer and expect it to receive the target string directly.
```

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +`grpc.NewClient` automatically ignores `DialOptions` returned by `WithBlock`, `WithTimeout`, `WithReturnConnectionError`, and `FailOnNonTempDialError.
```suggestion
`grpc.NewClient` automatically ignores `DialOptions` returned by `WithBlock`, `WithTimeout`, `WithReturnConnectionError`, and `FailOnNonTempDialError`. 
```

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
> +`grpc.NewClient` uses passthrough as the default name resolver for backward compatibility while  `Dial` uses dns as its default name resolver. This subtle diffrence is crucial in legacy systems that
`grpc.NewClient` uses `dns` and `grpc.Dial` uses `passthrough`

2024-04-15 22:23 UTC, arvindbr8 commented on Documentation/anti-patterns.md
I'm not fully convinced that this is the correct place for this documentation to go to. How about we revert the changes here, and someone internal could possibly pick up how the messaging should look like.

2024-04-17 23:34 UTC, arvindbr8 commented
@silaselisha -- I've addressed my comments and pushed a new commit to your branch. I think it looks good now. Per policy we would want one more review on the PR from our maintainers. cc: @zasweq, could you please take a pass at the documentation update and the other diffs

2024-04-17 23:34 UTC, arvindbr8 approved these changes

2024-04-18 00:50 UTC, zasweq commented
Giving to Abhishek since he's on call.

2024-04-19 12:36 UTC, aranjans approved these changes

2024-04-19 12:37 UTC, aranjans commented
LGTM!

2024-04-19 17:46 UTC, arvindbr8 approved these changes

2024-04-19 17:55 UTC, arvindbr8 commented
Thanks for the PR @silaselisha.

2024-04-19 17:55 UTC, merged