alts: fix defer in test
grpc/grpc-go pull request #7270
Opened 2024-05-25 16:40 UTC by arp242

The first () calls the function immediately, and the second calls the returned function at the end.

Doesn't really matter here because there's just one test, but happened to find this while writing a linter for this and figured I might as well send a PR.

2024-05-29 06:13 UTC, aranjans requested changes
```
  temp := hsDialer
    hsDialer = func(target string, opts ...grpc.DialOption) (*grpc.ClientConn, error) {
        return &grpc.ClientConn{}, nil
    }
    defer func() {
        hsDialer = temp
    }()
```

2024-05-29 06:14 UTC, aranjans commented
@arp242 Overall it looks good to me, just a small nit [here](https://github.com/grpc/grpc-go/pull/7270#pullrequestreview-2084361863)

2024-05-29 19:00 UTC, arp242 commented
I'm not really sure what you're asking, and I don't really have much interest in this project. Just found this and thought I'd report it, and creating a PR is (almost) as easy as making an issue. Please just make the changes yourself by modifying this PR or opening a new and closing this (adding `()` doesn't qualify for copyright; whatever is fine with me).

2024-05-30 05:45 UTC, aranjans requested changes
```
  temp := hsDialer
    hsDialer = func(target string, opts ...grpc.DialOption) (*grpc.ClientConn, error) {
        return &grpc.ClientConn{}, nil
    }
    defer func() {
        hsDialer = temp
    }()
```

2024-05-30 05:48 UTC, closed without merging

2024-05-30 05:49 UTC, arp242 commented
I you want to fix this bug *and* make the code look nicer then you'll have to do it yourself.

2024-06-04 21:43 UTC, easwars commented
@arp242 : Thanks for pointing out the bug in our code. We will fix the bug on our side.

2024-06-04 22:47 UTC, arvindbr8 commented
> The first () calls the function immediately, and the second calls the returned function at the end.
Doesn't really matter here because there's just one test, but happened to find this while writing a linter for this and figured I might as well send a PR.

Thanks for catching this! The second call in the defer wasn't executing, which prevented the `hsDialer` restore (not convinced that a restoration is even required) 

We appreciate your PR and the keen eye for detail. As for the additional cleanup, there seems to be a bit of discussion on the best approach. While we value code elegance, we also want to prioritize fixing this testing bug promptly.

To keep things focused, we're inclined to reopen this PR as is, addressing the primary issue. We can then open a separate discussion for any refactoring or stylistic improvements. This way, we can move forward with the fix while still considering everyone's feedback.

We welcome all contributions and feedback, even (or especially!) from those who may not be gRPC's biggest fans. If you have specific concerns or suggestions about gRPC, we're happy to hear them.