Fix revive identified linter issues: redefines-builtin-id, empty-block
grpc/grpc-go pull request #7552
Opened 2024-08-22 19:25 UTC by janardhanvissa

#7444

Fixed below linter issues:

-  8 empty-block   
- 15 redefines-builtin-id  

Release Note: None

2024-08-26 13:40 UTC, janardhanvissa commented on balancer/grpclb/grpclb_test.go
> -		go func() {
this approach addresses the revive linter's warning about empty blocks

2024-08-26 13:58 UTC, janardhanvissa commented on balancer/rls/config.go
> +			break
balancer/rls/config.go:273:3: this block is empty, you can remove it https://revive.run/r#empty-block

This approach also addresses the revive linter's warning about empty blocks. Assumed there is only one entry in config and handled accordingly.

2024-08-26 14:09 UTC, janardhanvissa commented on internal/balancer/gracefulswitch/config.go
> +			break
internal/balancer/gracefulswitch/config.go:59:3: this block is empty, you can remove it https://revive.run/r#empty-block

This approach also addresses the revive linter's warning about empty blocks.

2024-08-26 14:09 UTC, janardhanvissa commented on internal/serviceconfig/serviceconfig.go
> +			break
internal/serviceconfig/serviceconfig.go:93:3: this block is empty, you can remove it https://revive.run/r#empty-block

This approach also addresses the revive linter's warning about empty blocks.

2024-08-26 14:10 UTC, janardhanvissa commented on test/channelz_test.go
> +			break
test/channelz_test.go:155:3: this block is empty, you can remove it https://revive.run/r#empty-block

This approach also addresses the revive linter's warning about empty blocks.

2024-08-26 14:10 UTC, janardhanvissa commented on test/channelz_test.go
> +			break
test/channelz_test.go:235:3: this block is empty, you can remove it https://revive.run/r#empty-block

This approach also addresses the revive linter's warning about empty blocks.

2024-08-27 07:20 UTC, purnesh42H commented on balancer/grpclb/grpclb_test.go
> -		go func() {
So, why would you remove it? its part of the test

In Go, a for range loop on a channel continues to read values from the channel until the channel is closed. If the channel is not closed, the loop will block, waiting for more values to be sent on the channel.

2024-08-27 09:41 UTC, janardhanvissa commented on balancer/grpclb/grpclb_test.go
> -		go func() {
@purnesh42H Reverted the change but refactored to a separate method. Is that fine?

2024-08-27 12:07 UTC, purnesh42H commented on balancer/grpclb/grpclb_test.go
> -		go func() {
I think you can just put the comment inside `{ }` block

2024-08-27 12:08 UTC, purnesh42H commented on balancer/rls/config.go
> +			break
same. add the comment inside loop block instead of break. We don't want to change the behavior of the test. Please do everywhere

2024-08-27 12:09 UTC, janardhanvissa commented on balancer/grpclb/grpclb_test.go
> -		go func() {
Comment added like 'Continue draining until the channel is closed'

2024-08-27 18:16 UTC, purnesh42H commented on balancer/grpclb/grpclb_test.go
> -		go func() {
don't delete the go routine. just modify the existing go routine by putting comment inside `{ }` block

2024-08-27 18:16 UTC, purnesh42H commented on balancer/rls/config.go
> +			// extracting the policy/config pair
// loop until end to get the last config

2024-08-27 18:16 UTC, purnesh42H commented on clientconn_test.go
> +		// Continuously read from the connection until an error occurs
// keep reading until something causes the connection to die

2024-08-27 18:16 UTC, purnesh42H commented on internal/balancer/gracefulswitch/config.go
> +			// extract the policy name and policy config from the map entry.
// loop until end to get the last config

2024-08-27 18:16 UTC, purnesh42H commented on internal/serviceconfig/serviceconfig.go
> +			// extract the policy name and configuration from the map entry.
// loop until end to get the last config

2024-08-27 18:16 UTC, purnesh42H commented on test/channelz_test.go
> +			// extract the socket id from the map entry.
// loop until end to get the last subchannel id

2024-08-27 18:16 UTC, purnesh42H commented on test/channelz_test.go
> +			// extract the socket id from the map entry.
loop until end to get the last to get last socket id

2024-08-27 18:16 UTC, purnesh42H commented
@janardhanvissa make sure to keep the comments upto line col 80

2024-08-27 18:59 UTC, janardhanvissa commented
@purnesh42H Updated the comments as suggested and pushed the changes. Please re-review it.

2024-08-28 14:43 UTC, purnesh42H commented on test/channelz_test.go
> +			// loop until end to get the last to get last socket id
// loop until end to get the last socket id

2024-08-28 14:43 UTC, purnesh42H commented on test/clientconn_state_transition_test.go
> +		// Continuously read from the connection until an error occurs
// Keep reading until something causes the connection to die

2024-08-28 14:44 UTC, purnesh42H approved these changes
lgtm. Please fix the grammer as suggested in 2 new comments

2024-08-28 17:05 UTC, janardhanvissa commented
@purnesh42H Both the above-mentioned comments addressed and pushed the changes.

2024-08-29 18:31 UTC, arvindbr8 requested changes
I see 8 more `empty-block` in the lint run. Could you take another look?

2024-08-29 18:31 UTC, arvindbr8 commented on balancer_wrapper.go
> +		p, cleanup := pb.Build(acbw)
`cleanup` isnt right here.  How about `closeF` ?

2024-08-29 18:31 UTC, arvindbr8 commented on orca/producer.go
> +	pr, cleanup := sc.GetOrBuildProducer(producerBuilderSingleton)
```suggestion
	pr, closeF := sc.GetOrBuildProducer(producerBuilderSingleton)
```

2024-08-29 18:31 UTC, arvindbr8 commented on internal/xds/rbac/converter.go
> +	unmarshalledConfig, err := config.UnmarshalNew()
```suggestion
	c, err := config.UnmarshalNew()
```

2024-08-29 18:31 UTC, arvindbr8 commented on internal/status/status.go
> +		anyMsg, err := anypb.New(protoadapt.MessageV2Of(detail))
```suggestion
		m, err := anypb.New(protoadapt.MessageV2Of(detail))
```

2024-08-29 18:31 UTC, arvindbr8 commented on internal/serviceconfig/serviceconfig.go
> +			// loop until end to get the last config
this doesn't fix the linter apparently. See: https://github.com/grpc/grpc-go/actions/runs/10601061265/job/29380009870?pr=7552#step:7:2286

2024-08-29 18:31 UTC, arvindbr8 commented on balancer/rls/config.go
> +			// loop until end to get the last config
same here: https://github.com/grpc/grpc-go/actions/runs/10601061265/job/29380009870?pr=7552#step:7:2415

2024-08-30 07:16 UTC, purnesh42H commented
Thanks @arvindbr8 for rechecking the empty blocks. I thought github UI will prompt if not fixed but looks like it doesn't always.

empty block for loops seems to be a recognized pattern in go. Adding inline comments doesn't seem to satisfy the linter. We can either do a noop operation inside like `_ = struct{}{} // Satisfy linter, effectively a no-op` or just disable the empty-block check.

@dfawley @arvindbr8 for thoughts

2024-08-30 13:36 UTC, janardhanvissa commented
Above mentioned comments are addressed and pushed the changes.

2024-09-03 19:58 UTC, purnesh42H approved these changes
lgtm

2024-09-03 20:01 UTC, purnesh42H commented
> Thanks @arvindbr8 for rechecking the empty blocks. I thought github UI will prompt if not fixed but looks like it doesn't always.
> 
> empty block for loops seems to be a recognized pattern in go. Adding inline comments doesn't seem to satisfy the linter. We can either do a noop operation inside like `_ = struct{}{} // Satisfy linter, effectively a no-op` or just disable the empty-block check.
> 
> @dfawley @arvindbr8 for thoughts
Decided to undo `empty-block` changes. We will ignore them in the revive check

2024-09-05 06:08 UTC, purnesh42H commented on test/clientconn_state_transition_test.go
> +
@janardhanvissa revert this empty line please

2024-09-06 14:56 UTC, arvindbr8 approved these changes

2024-09-06 14:56 UTC, arvindbr8 commented on orca/producer.go
> +	pr, closeF := sc.GetOrBuildProducer(producerBuilderSingleton)
nit: 

```suggestion
	pr, closeFn := sc.GetOrBuildProducer(producerBuilderSingleton)
```

2024-09-06 18:09 UTC, janardhanvissa commented
@purnesh42H Updated close to closeFn as mentioned above. Please re-review the changes.

2024-09-07 20:06 UTC, merged

2024-09-09 16:49 UTC, arvindbr8 commented
We should have probably rebased and removed [this](https://github.com/grpc/grpc-go/blob/master/scripts/revive.toml#L31) TODO.

2024-09-12 05:26 UTC, purnesh42H commented
> We should have probably rebased and removed [this](https://github.com/grpc/grpc-go/blob/master/scripts/revive.toml#L31) TODO.

https://github.com/grpc/grpc-go/pull/7575

2024-09-12 05:26 UTC, purnesh42H commented
> > We should have probably rebased and removed [this](https://github.com/grpc/grpc-go/blob/master/scripts/revive.toml#L31) TODO.
> 
> Ah yeah i will remove both after #7575