test: modify tests to use stubserver instead of test service
grpc/grpc-go pull request #7976
Opened 2024-12-31 10:06 UTC by pvsravani

Partially Addresses: #7291

RELEASE NOTES: None

2025-01-03 06:26 UTC, purnesh42H commented on test/healthcheck_test.go
> +	t.Cleanup(func() { stub.Stop() })
should be `stub.S.Stop()`

2025-01-03 06:26 UTC, purnesh42H commented on test/stats_test.go
> +		errCh <- ss.S.Serve(ss.Listener)
we should remove the redundant `Serve` since `StartTestService` already start the server. This has to be followed for every change. Please keep in mind for future changes.

2025-01-03 06:59 UTC, pvsravani commented on test/healthcheck_test.go
> +	t.Cleanup(func() { stub.Stop() })
Done

2025-01-03 07:00 UTC, pvsravani commented on test/stats_test.go
> +		errCh <- ss.S.Serve(ss.Listener)
Done.

2025-01-03 07:43 UTC, janardhanvissa reviewed
LGTM!

2025-01-06 18:15 UTC, purnesh42H requested changes

2025-01-06 18:15 UTC, purnesh42H commented on test/healthcheck_test.go
> +		EmptyCallF: func(_ context.Context, _ *testpb.Empty) (*testpb.Empty, error) {
From where did this EmptyCallF and FullDuplexCallF implementation taken from? How is this being used? I can't find it. The testServer{} has totally different implementation here https://github.com/grpc/grpc-go/blob/724f450f77a09bade8174e5052625977069aaf81/test/end2end_test.go#L150

2025-01-06 18:15 UTC, purnesh42H commented on xds/internal/server/listener_wrapper_test.go
> +	ss.S.Stop()
this should be done right after `stubserver.StartTestService()`  as defer statement.

2025-01-10 07:33 UTC, pvsravani commented on xds/internal/server/listener_wrapper_test.go
> +	ss.S.Stop()
Done

2025-01-16 16:43 UTC, purnesh42H commented
@pvsravani @janardhanvissa could you please provide update on this? If you are not going to work on it, please close the PR and reopen once ready for review

2025-01-17 08:20 UTC, purnesh42H commented
@pvsravani i am closing the PR for now. Please reopen once broken tests are fixed.

2025-01-17 08:20 UTC, closed without merging